version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: root
            DB_TEST_HOST: db
            DB_TEST_PORT: 3306
            DB_TEST_DATABASE: laravel_test
            DB_TEST_USERNAME: root
            DB_TEST_PASSWORD: root
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports:
            - "3306:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
